services:
  slurm:
    image: ${SLURM_DOCKER_IMAGE:-giovtorres/slurm-docker:25.11.2}
    hostname: slurmctl
    container_name: slurmctl
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /pyslurm
    environment:
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - ${PWD}:/pyslurm:z
