#include "stdio.h"


// this is the enum defining slurm message types in 21.08
// src/common/slurm_protocol_defs.h

typedef enum {
	REQUEST_NODE_REGISTRATION_STATUS = 1001,
	MESSAGE_NODE_REGISTRATION_STATUS,
	REQUEST_RECONFIGURE,
	REQUEST_RECONFIGURE_WITH_CONFIG,
	REQUEST_SHUTDOWN,
	DEFUNCT_RPC_1006,
	DEFUNCT_RPC_1007,
	REQUEST_PING,
	REQUEST_CONTROL,
	REQUEST_SET_DEBUG_LEVEL,	/* 1010 */
	REQUEST_HEALTH_CHECK,
	REQUEST_TAKEOVER,
	REQUEST_SET_SCHEDLOG_LEVEL,
	REQUEST_SET_DEBUG_FLAGS,
	REQUEST_REBOOT_NODES,
	RESPONSE_PING_SLURMD,
	REQUEST_ACCT_GATHER_UPDATE,
	RESPONSE_ACCT_GATHER_UPDATE,
	REQUEST_ACCT_GATHER_ENERGY,
	RESPONSE_ACCT_GATHER_ENERGY,	/* 1020 */
	REQUEST_LICENSE_INFO,
	RESPONSE_LICENSE_INFO,
	REQUEST_SET_FS_DAMPENING_FACTOR,
	RESPONSE_NODE_REGISTRATION,

	PERSIST_RC = 1433, /* To mirror the DBD_RC this is replacing */
	/* Don't make any messages in this range as this is what the DBD uses
	 * unless mirroring */
	DBD_MESSAGES_END	= 2000,

	REQUEST_BUILD_INFO	= 2001,
	RESPONSE_BUILD_INFO,
	REQUEST_JOB_INFO,
	RESPONSE_JOB_INFO,
	REQUEST_JOB_STEP_INFO,
	RESPONSE_JOB_STEP_INFO,
	REQUEST_NODE_INFO,
	RESPONSE_NODE_INFO,
	REQUEST_PARTITION_INFO,
	RESPONSE_PARTITION_INFO,	/* 2010 */
	DEFUNCT_RPC_2011,
	DEFUNCT_RPC_2012,
	REQUEST_JOB_ID,
	RESPONSE_JOB_ID,
	REQUEST_CONFIG,
	RESPONSE_CONFIG,
	REQUEST_TRIGGER_SET,
	REQUEST_TRIGGER_GET,
	REQUEST_TRIGGER_CLEAR,
	RESPONSE_TRIGGER_GET,		/* 2020 */
	REQUEST_JOB_INFO_SINGLE,
	REQUEST_SHARE_INFO,
	RESPONSE_SHARE_INFO,
	REQUEST_RESERVATION_INFO,
	RESPONSE_RESERVATION_INFO,
	REQUEST_PRIORITY_FACTORS,
	RESPONSE_PRIORITY_FACTORS,
	REQUEST_TOPO_INFO,
	RESPONSE_TOPO_INFO,
	REQUEST_TRIGGER_PULL,		/* 2030 */
	REQUEST_FRONT_END_INFO,
	RESPONSE_FRONT_END_INFO,
	DEFUNCT_RPC_2033,
	DEFUNCT_RPC_2034,
	REQUEST_STATS_INFO,
	RESPONSE_STATS_INFO,
	REQUEST_BURST_BUFFER_INFO,
	RESPONSE_BURST_BUFFER_INFO,
	REQUEST_JOB_USER_INFO,
	REQUEST_NODE_INFO_SINGLE,	/* 2040 */
	DEFUNCT_RPC_2041,
	DEFUNCT_RPC_2042,
	REQUEST_ASSOC_MGR_INFO,
	RESPONSE_ASSOC_MGR_INFO,
	DEFUNCT_RPC_2045,
	DEFUNCT_RPC_2046, /* free for reuse */
	DEFUNCT_RPC_2047,
	DEFUNCT_RPC_2048,
	REQUEST_FED_INFO,
	RESPONSE_FED_INFO,		/* 2050 */
	REQUEST_BATCH_SCRIPT,
	RESPONSE_BATCH_SCRIPT,
	REQUEST_CONTROL_STATUS,
	RESPONSE_CONTROL_STATUS,
	REQUEST_BURST_BUFFER_STATUS,
	RESPONSE_BURST_BUFFER_STATUS,

	REQUEST_CRONTAB = 2200,
	RESPONSE_CRONTAB,
	REQUEST_UPDATE_CRONTAB,
	RESPONSE_UPDATE_CRONTAB,

	REQUEST_UPDATE_JOB = 3001,
	REQUEST_UPDATE_NODE,
	REQUEST_CREATE_PARTITION,
	REQUEST_DELETE_PARTITION,
	REQUEST_UPDATE_PARTITION,
	REQUEST_CREATE_RESERVATION,
	RESPONSE_CREATE_RESERVATION,
	REQUEST_DELETE_RESERVATION,
	REQUEST_UPDATE_RESERVATION,
	DEFUNCT_RPC_3010,  /* free for reuse */
	REQUEST_UPDATE_FRONT_END,		/* 3011 */
	DEFUNCT_RPC_3012,
	DEFUNCT_RPC_3013,

	REQUEST_RESOURCE_ALLOCATION = 4001,
	RESPONSE_RESOURCE_ALLOCATION,
	REQUEST_SUBMIT_BATCH_JOB,
	RESPONSE_SUBMIT_BATCH_JOB,
	REQUEST_BATCH_JOB_LAUNCH,
	REQUEST_CANCEL_JOB,
	DEFUNCT_RPC_4007,
	DEFUNCT_RPC_4008,
	DEFUNCT_RPC_4009,
	DEFUNCT_RPC_4010,		/* 4010 */
	DEFUNCT_RPC_4011,
	REQUEST_JOB_WILL_RUN,
	RESPONSE_JOB_WILL_RUN,
	REQUEST_JOB_ALLOCATION_INFO,
	RESPONSE_JOB_ALLOCATION_INFO,
	DEFUNCT_RPC_4017, /* free for reuse */
	DEFUNCT_RPC_4018, /* free for reuse */
	DEFUNCT_RPC_4019,
	REQUEST_JOB_READY,
	RESPONSE_JOB_READY,		/* 4020 */
	REQUEST_JOB_END_TIME,
	REQUEST_JOB_NOTIFY,
	REQUEST_JOB_SBCAST_CRED,
	RESPONSE_JOB_SBCAST_CRED,
	REQUEST_HET_JOB_ALLOCATION,
	RESPONSE_HET_JOB_ALLOCATION,
	REQUEST_HET_JOB_ALLOC_INFO,
	REQUEST_SUBMIT_BATCH_HET_JOB,

	REQUEST_CTLD_MULT_MSG = 4500,
	RESPONSE_CTLD_MULT_MSG,
	REQUEST_SIB_MSG,
	REQUEST_SIB_JOB_LOCK,
	REQUEST_SIB_JOB_UNLOCK,
	REQUEST_SEND_DEP,
	REQUEST_UPDATE_ORIGIN_DEP,

	REQUEST_JOB_STEP_CREATE = 5001,
	RESPONSE_JOB_STEP_CREATE,
	DEFUNCT_RPC_5003,
	DEFUNCT_RPC_5004,
	REQUEST_CANCEL_JOB_STEP,
	DEFUNCT_RPC_5006,
	REQUEST_UPDATE_JOB_STEP,
	DEFUNCT_RPC_5008,
	DEFUNCT_RPC_5009,
	DEFUNCT_RPC_5010,		/* 5010 */
	DEFUNCT_RPC_5011,
	DEFUNCT_RPC_5012,
	DEFUNCT_RPC_5013,
	REQUEST_SUSPEND,
	DEFUNCT_RPC_5015,
	REQUEST_STEP_COMPLETE,
	REQUEST_COMPLETE_JOB_ALLOCATION,
	REQUEST_COMPLETE_BATCH_SCRIPT,
	REQUEST_JOB_STEP_STAT,
	RESPONSE_JOB_STEP_STAT,		/* 5020 */
	REQUEST_STEP_LAYOUT,
	RESPONSE_STEP_LAYOUT,
	REQUEST_JOB_REQUEUE,
	REQUEST_DAEMON_STATUS,
	RESPONSE_SLURMD_STATUS,
	DEFUNCT_RPC_5026,
	REQUEST_JOB_STEP_PIDS,
	RESPONSE_JOB_STEP_PIDS,
	REQUEST_FORWARD_DATA,
	DEFUNCT_RPC_5030,		/* 5030 */
	REQUEST_SUSPEND_INT,
	REQUEST_KILL_JOB,		/* 5032 */
	DEFUNCT_RPC_5033,
	RESPONSE_JOB_ARRAY_ERRORS,
	REQUEST_NETWORK_CALLERID,
	RESPONSE_NETWORK_CALLERID,
	DEFUNCT_RPC_5037,
	REQUEST_TOP_JOB,		/* 5038 */
	REQUEST_AUTH_TOKEN,
	RESPONSE_AUTH_TOKEN,

	REQUEST_LAUNCH_TASKS = 6001,
	RESPONSE_LAUNCH_TASKS,
	MESSAGE_TASK_EXIT,
	REQUEST_SIGNAL_TASKS,
	DEFUNCT_RPC_6005,
	REQUEST_TERMINATE_TASKS,
	REQUEST_REATTACH_TASKS,
	RESPONSE_REATTACH_TASKS,
	REQUEST_KILL_TIMELIMIT,
	DEFUNCT_RPC_6010, /* free for reuse */
	REQUEST_TERMINATE_JOB,		/* 6011 */
	MESSAGE_EPILOG_COMPLETE,
	REQUEST_ABORT_JOB,	/* job shouldn't be running, kill it without
				 * job/step/task complete responses */
	REQUEST_FILE_BCAST,
	TASK_USER_MANAGED_IO_STREAM,
	REQUEST_KILL_PREEMPTED,

	REQUEST_LAUNCH_PROLOG,
	REQUEST_COMPLETE_PROLOG,
	RESPONSE_PROLOG_EXECUTING,	/* 6019 */

	REQUEST_PERSIST_INIT = 6500,

	SRUN_PING = 7001,
	SRUN_TIMEOUT,
	SRUN_NODE_FAIL,
	SRUN_JOB_COMPLETE,
	SRUN_USER_MSG,
	SRUN_EXEC,
	SRUN_STEP_MISSING,
	SRUN_REQUEST_SUSPEND,
	SRUN_STEP_SIGNAL,	/* for launch plugins aprun and poe,
				 * srun forwards signal to the launch command */
	SRUN_NET_FORWARD,

	PMI_KVS_PUT_REQ = 7201,
	DEFUNCT_RPC_7202,
	PMI_KVS_GET_REQ,
	PMI_KVS_GET_RESP,

	RESPONSE_SLURM_RC = 8001,
	RESPONSE_SLURM_RC_MSG,
	RESPONSE_SLURM_REROUTE_MSG,

	RESPONSE_FORWARD_FAILED = 9001,

	ACCOUNTING_UPDATE_MSG = 10001,
	ACCOUNTING_FIRST_REG,
	ACCOUNTING_REGISTER_CTLD,
	ACCOUNTING_TRES_CHANGE_DB,
	ACCOUNTING_NODES_CHANGE_DB,
} slurm_msg_type_t;



// autogenerated code to print the protocol enum in python dict format
int main(void) {
	
    printf("%d: \"%s\",\n", REQUEST_NODE_REGISTRATION_STATUS, "REQUEST_NODE_REGISTRATION_STATUS");
    printf("%d: \"%s\",\n", MESSAGE_NODE_REGISTRATION_STATUS, "MESSAGE_NODE_REGISTRATION_STATUS");
    printf("%d: \"%s\",\n", REQUEST_RECONFIGURE, "REQUEST_RECONFIGURE");
    printf("%d: \"%s\",\n", REQUEST_RECONFIGURE_WITH_CONFIG, "REQUEST_RECONFIGURE_WITH_CONFIG");
    printf("%d: \"%s\",\n", REQUEST_SHUTDOWN, "REQUEST_SHUTDOWN");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_1006, "DEFUNCT_RPC_1006");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_1007, "DEFUNCT_RPC_1007");
    printf("%d: \"%s\",\n", REQUEST_PING, "REQUEST_PING");
    printf("%d: \"%s\",\n", REQUEST_CONTROL, "REQUEST_CONTROL");
    printf("%d: \"%s\",\n", REQUEST_SET_DEBUG_LEVEL, "REQUEST_SET_DEBUG_LEVEL");
    printf("%d: \"%s\",\n", REQUEST_HEALTH_CHECK, "REQUEST_HEALTH_CHECK");
    printf("%d: \"%s\",\n", REQUEST_TAKEOVER, "REQUEST_TAKEOVER");
    printf("%d: \"%s\",\n", REQUEST_SET_SCHEDLOG_LEVEL, "REQUEST_SET_SCHEDLOG_LEVEL");
    printf("%d: \"%s\",\n", REQUEST_SET_DEBUG_FLAGS, "REQUEST_SET_DEBUG_FLAGS");
    printf("%d: \"%s\",\n", REQUEST_REBOOT_NODES, "REQUEST_REBOOT_NODES");
    printf("%d: \"%s\",\n", RESPONSE_PING_SLURMD, "RESPONSE_PING_SLURMD");
    printf("%d: \"%s\",\n", REQUEST_ACCT_GATHER_UPDATE, "REQUEST_ACCT_GATHER_UPDATE");
    printf("%d: \"%s\",\n", RESPONSE_ACCT_GATHER_UPDATE, "RESPONSE_ACCT_GATHER_UPDATE");
    printf("%d: \"%s\",\n", REQUEST_ACCT_GATHER_ENERGY, "REQUEST_ACCT_GATHER_ENERGY");
    printf("%d: \"%s\",\n", RESPONSE_ACCT_GATHER_ENERGY, "RESPONSE_ACCT_GATHER_ENERGY");
    printf("%d: \"%s\",\n", REQUEST_LICENSE_INFO, "REQUEST_LICENSE_INFO");
    printf("%d: \"%s\",\n", RESPONSE_LICENSE_INFO, "RESPONSE_LICENSE_INFO");
    printf("%d: \"%s\",\n", REQUEST_SET_FS_DAMPENING_FACTOR, "REQUEST_SET_FS_DAMPENING_FACTOR");
    printf("%d: \"%s\",\n", RESPONSE_NODE_REGISTRATION, "RESPONSE_NODE_REGISTRATION");
    printf("%d: \"%s\",\n", PERSIST_RC, "PERSIST_RC");
    printf("%d: \"%s\",\n", DBD_MESSAGES_END, "DBD_MESSAGES_END");
    printf("%d: \"%s\",\n", REQUEST_BUILD_INFO, "REQUEST_BUILD_INFO");
    printf("%d: \"%s\",\n", RESPONSE_BUILD_INFO, "RESPONSE_BUILD_INFO");
    printf("%d: \"%s\",\n", REQUEST_JOB_INFO, "REQUEST_JOB_INFO");
    printf("%d: \"%s\",\n", RESPONSE_JOB_INFO, "RESPONSE_JOB_INFO");
    printf("%d: \"%s\",\n", REQUEST_JOB_STEP_INFO, "REQUEST_JOB_STEP_INFO");
    printf("%d: \"%s\",\n", RESPONSE_JOB_STEP_INFO, "RESPONSE_JOB_STEP_INFO");
    printf("%d: \"%s\",\n", REQUEST_NODE_INFO, "REQUEST_NODE_INFO");
    printf("%d: \"%s\",\n", RESPONSE_NODE_INFO, "RESPONSE_NODE_INFO");
    printf("%d: \"%s\",\n", REQUEST_PARTITION_INFO, "REQUEST_PARTITION_INFO");
    printf("%d: \"%s\",\n", RESPONSE_PARTITION_INFO, "RESPONSE_PARTITION_INFO");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_2011, "DEFUNCT_RPC_2011");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_2012, "DEFUNCT_RPC_2012");
    printf("%d: \"%s\",\n", REQUEST_JOB_ID, "REQUEST_JOB_ID");
    printf("%d: \"%s\",\n", RESPONSE_JOB_ID, "RESPONSE_JOB_ID");
    printf("%d: \"%s\",\n", REQUEST_CONFIG, "REQUEST_CONFIG");
    printf("%d: \"%s\",\n", RESPONSE_CONFIG, "RESPONSE_CONFIG");
    printf("%d: \"%s\",\n", REQUEST_TRIGGER_SET, "REQUEST_TRIGGER_SET");
    printf("%d: \"%s\",\n", REQUEST_TRIGGER_GET, "REQUEST_TRIGGER_GET");
    printf("%d: \"%s\",\n", REQUEST_TRIGGER_CLEAR, "REQUEST_TRIGGER_CLEAR");
    printf("%d: \"%s\",\n", RESPONSE_TRIGGER_GET, "RESPONSE_TRIGGER_GET");
    printf("%d: \"%s\",\n", REQUEST_JOB_INFO_SINGLE, "REQUEST_JOB_INFO_SINGLE");
    printf("%d: \"%s\",\n", REQUEST_SHARE_INFO, "REQUEST_SHARE_INFO");
    printf("%d: \"%s\",\n", RESPONSE_SHARE_INFO, "RESPONSE_SHARE_INFO");
    printf("%d: \"%s\",\n", REQUEST_RESERVATION_INFO, "REQUEST_RESERVATION_INFO");
    printf("%d: \"%s\",\n", RESPONSE_RESERVATION_INFO, "RESPONSE_RESERVATION_INFO");
    printf("%d: \"%s\",\n", REQUEST_PRIORITY_FACTORS, "REQUEST_PRIORITY_FACTORS");
    printf("%d: \"%s\",\n", RESPONSE_PRIORITY_FACTORS, "RESPONSE_PRIORITY_FACTORS");
    printf("%d: \"%s\",\n", REQUEST_TOPO_INFO, "REQUEST_TOPO_INFO");
    printf("%d: \"%s\",\n", RESPONSE_TOPO_INFO, "RESPONSE_TOPO_INFO");
    printf("%d: \"%s\",\n", REQUEST_TRIGGER_PULL, "REQUEST_TRIGGER_PULL");
    printf("%d: \"%s\",\n", REQUEST_FRONT_END_INFO, "REQUEST_FRONT_END_INFO");
    printf("%d: \"%s\",\n", RESPONSE_FRONT_END_INFO, "RESPONSE_FRONT_END_INFO");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_2033, "DEFUNCT_RPC_2033");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_2034, "DEFUNCT_RPC_2034");
    printf("%d: \"%s\",\n", REQUEST_STATS_INFO, "REQUEST_STATS_INFO");
    printf("%d: \"%s\",\n", RESPONSE_STATS_INFO, "RESPONSE_STATS_INFO");
    printf("%d: \"%s\",\n", REQUEST_BURST_BUFFER_INFO, "REQUEST_BURST_BUFFER_INFO");
    printf("%d: \"%s\",\n", RESPONSE_BURST_BUFFER_INFO, "RESPONSE_BURST_BUFFER_INFO");
    printf("%d: \"%s\",\n", REQUEST_JOB_USER_INFO, "REQUEST_JOB_USER_INFO");
    printf("%d: \"%s\",\n", REQUEST_NODE_INFO_SINGLE, "REQUEST_NODE_INFO_SINGLE");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_2041, "DEFUNCT_RPC_2041");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_2042, "DEFUNCT_RPC_2042");
    printf("%d: \"%s\",\n", REQUEST_ASSOC_MGR_INFO, "REQUEST_ASSOC_MGR_INFO");
    printf("%d: \"%s\",\n", RESPONSE_ASSOC_MGR_INFO, "RESPONSE_ASSOC_MGR_INFO");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_2045, "DEFUNCT_RPC_2045");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_2046, "DEFUNCT_RPC_2046");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_2047, "DEFUNCT_RPC_2047");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_2048, "DEFUNCT_RPC_2048");
    printf("%d: \"%s\",\n", REQUEST_FED_INFO, "REQUEST_FED_INFO");
    printf("%d: \"%s\",\n", RESPONSE_FED_INFO, "RESPONSE_FED_INFO");
    printf("%d: \"%s\",\n", REQUEST_BATCH_SCRIPT, "REQUEST_BATCH_SCRIPT");
    printf("%d: \"%s\",\n", RESPONSE_BATCH_SCRIPT, "RESPONSE_BATCH_SCRIPT");
    printf("%d: \"%s\",\n", REQUEST_CONTROL_STATUS, "REQUEST_CONTROL_STATUS");
    printf("%d: \"%s\",\n", RESPONSE_CONTROL_STATUS, "RESPONSE_CONTROL_STATUS");
    printf("%d: \"%s\",\n", REQUEST_BURST_BUFFER_STATUS, "REQUEST_BURST_BUFFER_STATUS");
    printf("%d: \"%s\",\n", RESPONSE_BURST_BUFFER_STATUS, "RESPONSE_BURST_BUFFER_STATUS");
    printf("%d: \"%s\",\n", REQUEST_CRONTAB, "REQUEST_CRONTAB");
    printf("%d: \"%s\",\n", RESPONSE_CRONTAB, "RESPONSE_CRONTAB");
    printf("%d: \"%s\",\n", REQUEST_UPDATE_CRONTAB, "REQUEST_UPDATE_CRONTAB");
    printf("%d: \"%s\",\n", RESPONSE_UPDATE_CRONTAB, "RESPONSE_UPDATE_CRONTAB");
    printf("%d: \"%s\",\n", REQUEST_UPDATE_JOB, "REQUEST_UPDATE_JOB");
    printf("%d: \"%s\",\n", REQUEST_UPDATE_NODE, "REQUEST_UPDATE_NODE");
    printf("%d: \"%s\",\n", REQUEST_CREATE_PARTITION, "REQUEST_CREATE_PARTITION");
    printf("%d: \"%s\",\n", REQUEST_DELETE_PARTITION, "REQUEST_DELETE_PARTITION");
    printf("%d: \"%s\",\n", REQUEST_UPDATE_PARTITION, "REQUEST_UPDATE_PARTITION");
    printf("%d: \"%s\",\n", REQUEST_CREATE_RESERVATION, "REQUEST_CREATE_RESERVATION");
    printf("%d: \"%s\",\n", RESPONSE_CREATE_RESERVATION, "RESPONSE_CREATE_RESERVATION");
    printf("%d: \"%s\",\n", REQUEST_DELETE_RESERVATION, "REQUEST_DELETE_RESERVATION");
    printf("%d: \"%s\",\n", REQUEST_UPDATE_RESERVATION, "REQUEST_UPDATE_RESERVATION");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_3010, "DEFUNCT_RPC_3010");
    printf("%d: \"%s\",\n", REQUEST_UPDATE_FRONT_END, "REQUEST_UPDATE_FRONT_END");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_3012, "DEFUNCT_RPC_3012");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_3013, "DEFUNCT_RPC_3013");
    printf("%d: \"%s\",\n", REQUEST_RESOURCE_ALLOCATION, "REQUEST_RESOURCE_ALLOCATION");
    printf("%d: \"%s\",\n", RESPONSE_RESOURCE_ALLOCATION, "RESPONSE_RESOURCE_ALLOCATION");
    printf("%d: \"%s\",\n", REQUEST_SUBMIT_BATCH_JOB, "REQUEST_SUBMIT_BATCH_JOB");
    printf("%d: \"%s\",\n", RESPONSE_SUBMIT_BATCH_JOB, "RESPONSE_SUBMIT_BATCH_JOB");
    printf("%d: \"%s\",\n", REQUEST_BATCH_JOB_LAUNCH, "REQUEST_BATCH_JOB_LAUNCH");
    printf("%d: \"%s\",\n", REQUEST_CANCEL_JOB, "REQUEST_CANCEL_JOB");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_4007, "DEFUNCT_RPC_4007");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_4008, "DEFUNCT_RPC_4008");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_4009, "DEFUNCT_RPC_4009");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_4010, "DEFUNCT_RPC_4010");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_4011, "DEFUNCT_RPC_4011");
    printf("%d: \"%s\",\n", REQUEST_JOB_WILL_RUN, "REQUEST_JOB_WILL_RUN");
    printf("%d: \"%s\",\n", RESPONSE_JOB_WILL_RUN, "RESPONSE_JOB_WILL_RUN");
    printf("%d: \"%s\",\n", REQUEST_JOB_ALLOCATION_INFO, "REQUEST_JOB_ALLOCATION_INFO");
    printf("%d: \"%s\",\n", RESPONSE_JOB_ALLOCATION_INFO, "RESPONSE_JOB_ALLOCATION_INFO");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_4017, "DEFUNCT_RPC_4017");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_4018, "DEFUNCT_RPC_4018");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_4019, "DEFUNCT_RPC_4019");
    printf("%d: \"%s\",\n", REQUEST_JOB_READY, "REQUEST_JOB_READY");
    printf("%d: \"%s\",\n", RESPONSE_JOB_READY, "RESPONSE_JOB_READY");
    printf("%d: \"%s\",\n", REQUEST_JOB_END_TIME, "REQUEST_JOB_END_TIME");
    printf("%d: \"%s\",\n", REQUEST_JOB_NOTIFY, "REQUEST_JOB_NOTIFY");
    printf("%d: \"%s\",\n", REQUEST_JOB_SBCAST_CRED, "REQUEST_JOB_SBCAST_CRED");
    printf("%d: \"%s\",\n", RESPONSE_JOB_SBCAST_CRED, "RESPONSE_JOB_SBCAST_CRED");
    printf("%d: \"%s\",\n", REQUEST_HET_JOB_ALLOCATION, "REQUEST_HET_JOB_ALLOCATION");
    printf("%d: \"%s\",\n", RESPONSE_HET_JOB_ALLOCATION, "RESPONSE_HET_JOB_ALLOCATION");
    printf("%d: \"%s\",\n", REQUEST_HET_JOB_ALLOC_INFO, "REQUEST_HET_JOB_ALLOC_INFO");
    printf("%d: \"%s\",\n", REQUEST_SUBMIT_BATCH_HET_JOB, "REQUEST_SUBMIT_BATCH_HET_JOB");
    printf("%d: \"%s\",\n", REQUEST_CTLD_MULT_MSG, "REQUEST_CTLD_MULT_MSG");
    printf("%d: \"%s\",\n", RESPONSE_CTLD_MULT_MSG, "RESPONSE_CTLD_MULT_MSG");
    printf("%d: \"%s\",\n", REQUEST_SIB_MSG, "REQUEST_SIB_MSG");
    printf("%d: \"%s\",\n", REQUEST_SIB_JOB_LOCK, "REQUEST_SIB_JOB_LOCK");
    printf("%d: \"%s\",\n", REQUEST_SIB_JOB_UNLOCK, "REQUEST_SIB_JOB_UNLOCK");
    printf("%d: \"%s\",\n", REQUEST_SEND_DEP, "REQUEST_SEND_DEP");
    printf("%d: \"%s\",\n", REQUEST_UPDATE_ORIGIN_DEP, "REQUEST_UPDATE_ORIGIN_DEP");
    printf("%d: \"%s\",\n", REQUEST_JOB_STEP_CREATE, "REQUEST_JOB_STEP_CREATE");
    printf("%d: \"%s\",\n", RESPONSE_JOB_STEP_CREATE, "RESPONSE_JOB_STEP_CREATE");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5003, "DEFUNCT_RPC_5003");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5004, "DEFUNCT_RPC_5004");
    printf("%d: \"%s\",\n", REQUEST_CANCEL_JOB_STEP, "REQUEST_CANCEL_JOB_STEP");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5006, "DEFUNCT_RPC_5006");
    printf("%d: \"%s\",\n", REQUEST_UPDATE_JOB_STEP, "REQUEST_UPDATE_JOB_STEP");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5008, "DEFUNCT_RPC_5008");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5009, "DEFUNCT_RPC_5009");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5010, "DEFUNCT_RPC_5010");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5011, "DEFUNCT_RPC_5011");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5012, "DEFUNCT_RPC_5012");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5013, "DEFUNCT_RPC_5013");
    printf("%d: \"%s\",\n", REQUEST_SUSPEND, "REQUEST_SUSPEND");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5015, "DEFUNCT_RPC_5015");
    printf("%d: \"%s\",\n", REQUEST_STEP_COMPLETE, "REQUEST_STEP_COMPLETE");
    printf("%d: \"%s\",\n", REQUEST_COMPLETE_JOB_ALLOCATION, "REQUEST_COMPLETE_JOB_ALLOCATION");
    printf("%d: \"%s\",\n", REQUEST_COMPLETE_BATCH_SCRIPT, "REQUEST_COMPLETE_BATCH_SCRIPT");
    printf("%d: \"%s\",\n", REQUEST_JOB_STEP_STAT, "REQUEST_JOB_STEP_STAT");
    printf("%d: \"%s\",\n", RESPONSE_JOB_STEP_STAT, "RESPONSE_JOB_STEP_STAT");
    printf("%d: \"%s\",\n", REQUEST_STEP_LAYOUT, "REQUEST_STEP_LAYOUT");
    printf("%d: \"%s\",\n", RESPONSE_STEP_LAYOUT, "RESPONSE_STEP_LAYOUT");
    printf("%d: \"%s\",\n", REQUEST_JOB_REQUEUE, "REQUEST_JOB_REQUEUE");
    printf("%d: \"%s\",\n", REQUEST_DAEMON_STATUS, "REQUEST_DAEMON_STATUS");
    printf("%d: \"%s\",\n", RESPONSE_SLURMD_STATUS, "RESPONSE_SLURMD_STATUS");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5026, "DEFUNCT_RPC_5026");
    printf("%d: \"%s\",\n", REQUEST_JOB_STEP_PIDS, "REQUEST_JOB_STEP_PIDS");
    printf("%d: \"%s\",\n", RESPONSE_JOB_STEP_PIDS, "RESPONSE_JOB_STEP_PIDS");
    printf("%d: \"%s\",\n", REQUEST_FORWARD_DATA, "REQUEST_FORWARD_DATA");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5030, "DEFUNCT_RPC_5030");
    printf("%d: \"%s\",\n", REQUEST_SUSPEND_INT, "REQUEST_SUSPEND_INT");
    printf("%d: \"%s\",\n", REQUEST_KILL_JOB, "REQUEST_KILL_JOB");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5033, "DEFUNCT_RPC_5033");
    printf("%d: \"%s\",\n", RESPONSE_JOB_ARRAY_ERRORS, "RESPONSE_JOB_ARRAY_ERRORS");
    printf("%d: \"%s\",\n", REQUEST_NETWORK_CALLERID, "REQUEST_NETWORK_CALLERID");
    printf("%d: \"%s\",\n", RESPONSE_NETWORK_CALLERID, "RESPONSE_NETWORK_CALLERID");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_5037, "DEFUNCT_RPC_5037");
    printf("%d: \"%s\",\n", REQUEST_TOP_JOB, "REQUEST_TOP_JOB");
    printf("%d: \"%s\",\n", REQUEST_AUTH_TOKEN, "REQUEST_AUTH_TOKEN");
    printf("%d: \"%s\",\n", RESPONSE_AUTH_TOKEN, "RESPONSE_AUTH_TOKEN");
    printf("%d: \"%s\",\n", REQUEST_LAUNCH_TASKS, "REQUEST_LAUNCH_TASKS");
    printf("%d: \"%s\",\n", RESPONSE_LAUNCH_TASKS, "RESPONSE_LAUNCH_TASKS");
    printf("%d: \"%s\",\n", MESSAGE_TASK_EXIT, "MESSAGE_TASK_EXIT");
    printf("%d: \"%s\",\n", REQUEST_SIGNAL_TASKS, "REQUEST_SIGNAL_TASKS");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_6005, "DEFUNCT_RPC_6005");
    printf("%d: \"%s\",\n", REQUEST_TERMINATE_TASKS, "REQUEST_TERMINATE_TASKS");
    printf("%d: \"%s\",\n", REQUEST_REATTACH_TASKS, "REQUEST_REATTACH_TASKS");
    printf("%d: \"%s\",\n", RESPONSE_REATTACH_TASKS, "RESPONSE_REATTACH_TASKS");
    printf("%d: \"%s\",\n", REQUEST_KILL_TIMELIMIT, "REQUEST_KILL_TIMELIMIT");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_6010, "DEFUNCT_RPC_6010");
    printf("%d: \"%s\",\n", REQUEST_TERMINATE_JOB, "REQUEST_TERMINATE_JOB");
    printf("%d: \"%s\",\n", MESSAGE_EPILOG_COMPLETE, "MESSAGE_EPILOG_COMPLETE");
    printf("%d: \"%s\",\n", REQUEST_ABORT_JOB, "REQUEST_ABORT_JOB");
    printf("%d: \"%s\",\n", REQUEST_FILE_BCAST, "REQUEST_FILE_BCAST");
    printf("%d: \"%s\",\n", TASK_USER_MANAGED_IO_STREAM, "TASK_USER_MANAGED_IO_STREAM");
    printf("%d: \"%s\",\n", REQUEST_KILL_PREEMPTED, "REQUEST_KILL_PREEMPTED");
    printf("%d: \"%s\",\n", REQUEST_LAUNCH_PROLOG, "REQUEST_LAUNCH_PROLOG");
    printf("%d: \"%s\",\n", REQUEST_COMPLETE_PROLOG, "REQUEST_COMPLETE_PROLOG");
    printf("%d: \"%s\",\n", RESPONSE_PROLOG_EXECUTING, "RESPONSE_PROLOG_EXECUTING");
    printf("%d: \"%s\",\n", REQUEST_PERSIST_INIT, "REQUEST_PERSIST_INIT");
    printf("%d: \"%s\",\n", SRUN_PING, "SRUN_PING");
    printf("%d: \"%s\",\n", SRUN_TIMEOUT, "SRUN_TIMEOUT");
    printf("%d: \"%s\",\n", SRUN_NODE_FAIL, "SRUN_NODE_FAIL");
    printf("%d: \"%s\",\n", SRUN_JOB_COMPLETE, "SRUN_JOB_COMPLETE");
    printf("%d: \"%s\",\n", SRUN_USER_MSG, "SRUN_USER_MSG");
    printf("%d: \"%s\",\n", SRUN_EXEC, "SRUN_EXEC");
    printf("%d: \"%s\",\n", SRUN_STEP_MISSING, "SRUN_STEP_MISSING");
    printf("%d: \"%s\",\n", SRUN_REQUEST_SUSPEND, "SRUN_REQUEST_SUSPEND");
    printf("%d: \"%s\",\n", SRUN_STEP_SIGNAL, "SRUN_STEP_SIGNAL");
    printf("%d: \"%s\",\n", SRUN_NET_FORWARD, "SRUN_NET_FORWARD");
    printf("%d: \"%s\",\n", PMI_KVS_PUT_REQ, "PMI_KVS_PUT_REQ");
    printf("%d: \"%s\",\n", DEFUNCT_RPC_7202, "DEFUNCT_RPC_7202");
    printf("%d: \"%s\",\n", PMI_KVS_GET_REQ, "PMI_KVS_GET_REQ");
    printf("%d: \"%s\",\n", PMI_KVS_GET_RESP, "PMI_KVS_GET_RESP");
    printf("%d: \"%s\",\n", RESPONSE_SLURM_RC, "RESPONSE_SLURM_RC");
    printf("%d: \"%s\",\n", RESPONSE_SLURM_RC_MSG, "RESPONSE_SLURM_RC_MSG");
    printf("%d: \"%s\",\n", RESPONSE_SLURM_REROUTE_MSG, "RESPONSE_SLURM_REROUTE_MSG");
    printf("%d: \"%s\",\n", RESPONSE_FORWARD_FAILED, "RESPONSE_FORWARD_FAILED");
    printf("%d: \"%s\",\n", ACCOUNTING_UPDATE_MSG, "ACCOUNTING_UPDATE_MSG");
    printf("%d: \"%s\",\n", ACCOUNTING_FIRST_REG, "ACCOUNTING_FIRST_REG");
    printf("%d: \"%s\",\n", ACCOUNTING_REGISTER_CTLD, "ACCOUNTING_REGISTER_CTLD");
    printf("%d: \"%s\",\n", ACCOUNTING_TRES_CHANGE_DB, "ACCOUNTING_TRES_CHANGE_DB");
    printf("%d: \"%s\",\n", ACCOUNTING_NODES_CHANGE_DB, "ACCOUNTING_NODES_CHANGE_DB");

    return 0;
}
