name: PySlurm

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Pull Slurm container
        run: docker pull giovtorres/slurm-docker:25.11.2

      - name: Start Slurm container
        run: docker compose up -d

      - name: Run unit tests
        run: scripts/run_tests.sh -u

      - name: Run integration tests
        run: scripts/run_tests.sh -s -i
